### ISSUE TITLE
Don't working for me

### ISSUE THREAD

**Issue by gyula21** [i-net-software/dokuwiki-plugin-pagetemplater#3]
I use the newliest Dokuwiki and the code what is in the description not add the template.
I used:
~~META:
templater page=:templates:kasztok-infobox
~~
which is a valid page.

**Comment by vchrizz** [comment]
for me it works with recent dokuwiki version: (you must use upper case!)

content of page template (in root):
====== @@PAGENAME@@ ======
@@PAGETEXT@@

content of page mypage (in root):
~~META:
templater page = :template
&templater pagename = MyPage1
&templater pagetext = Hello World
~~
