### ISSUE TITLE
remove newline on parsed properties

### ISSUE THREAD

**Issue by vchrizz** [i-net-software/dokuwiki-plugin-pagetemplater#4]
Hi,

I've read this:
Note: The page above defines a templater property using an exclamation mark (!) - this property will be fed into the DokuWiki XHTML renderer and produce rendered output.

But I don't quite understand where the newline is coming from, plugin or renderer?
On every property with exclamation mark there is a newline inserted. This doesn't look nice if you use lists and there is an empty line between list entries. Or if you want to add some pictures next to each other, they get displayed one below the other.

Guess this is just a small fix.

cheers

**Comment by vchrizz** [comment]
Please give a comment in why you closed this issue?

**Comment by gamma** [comment]
As stated above, the issue has been fixed. Please see the history of this issue ...

**Comment by vchrizz** [comment]
Great! Thanks!

**Comment by vchrizz** [comment]
just tested the fixed version, works really neat, as expected! thank you very much!
